### ISSUE TITLE
Support providing maven coordinates using libs.toml files

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/rules_jvm_external#976]
It would be great to support passing `libs.toml` files containing maven coordinates into `rules_jvm_external`.

I see a few benefits:
- Would help improve dependency management and let tools like `dependabot` and `renovate` help manage automatically bumping version updates.
- Would reduce the need to clutter our `MODULE.bazel` with giant lists of maven dependencies.

Potential issues:
- Conveying attributes like `testonly`, `neverlink`, and `packaging (aar|jar|...)` might be harder. Technically this is supported by the Toml format already but we would need to document this.

### Example:
```starlark
# MODULE.bazel
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    # Toml file containing all of the maven coords
    toml = "//:deps.toml",
)
```

```toml
# deps.toml
[versions]
androix-activity-version = "1.8.0"
androidx-experiemental-version = "1.3.0"
...

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", package = "aar", version.ref = "androix-activity-version" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", package = "aar", version.ref = "androix-activity-version" }
...
```
